# Generated by Django 4.0.2 on 2022-02-18 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_rating', models.IntegerField(default=0)),
                ('author_icon', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_header', models.CharField(max_length=64)),
                ('post_rating', models.IntegerField(default=0)),
                ('post_content', models.CharField(default='', max_length=512)),
                ('post_category', models.CharField(choices=[('t', 'Танки'), ('h', 'Хилы'), ('DD', 'ДД'), ('trad', 'Торговцы'), ('gild', 'Гилдмастеры'), ('qg', 'Квестгиверы'), ('bs', 'Кузнецы'), ('tan', 'Кожевники'), ('pot', 'Зельевары'), ('ms', 'Мастера заклинаний')], max_length=10)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMORPG.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=128)),
                ('comment_date_time', models.DateTimeField(auto_now_add=True)),
                ('comment_online', models.BooleanField(default=False)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMORPG.post')),
            ],
        ),
    ]
