# Generated by Django 4.0.2 on 2022-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMORPG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_code',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=32),
        ),
        migrations.AddField(
            model_name='author',
            name='author_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
