# Generated by Django 4.0.2 on 2022-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMORPG', '0002_author_author_code_author_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_code',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
