# Generated by Django 4.0.2 on 2022-02-16 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMORPG', '0004_alter_author_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_code',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_email',
        ),
    ]
