# Generated by Django 3.2.5 on 2021-07-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='None',
        ),
    ]
