# Generated by Django 3.2.5 on 2021-07-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210704_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
