# Generated by Django 3.2.5 on 2021-07-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_rename_category_category_name_of_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_of_category',
            new_name='name',
        ),
    ]
