# Generated by Django 3.2.5 on 2021-07-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Не указано', max_length=255),
        ),
    ]
