# Generated by Django 3.2.5 on 2021-07-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210704_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='pseudonym',
        ),
    ]
