# Generated by Django 3.2.5 on 2021-07-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_author_pseudonym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Sport',
        ),
        migrations.RemoveField(
            model_name='category',
            name='education',
        ),
        migrations.RemoveField(
            model_name='category',
            name='politician',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(default='None', max_length=10, unique=True),
        ),
    ]
