# Generated by Django 3.2.5 on 2021-07-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_name_of_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='prev',
        ),
    ]
