# Generated by Django 3.2.5 on 2021-07-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20210708_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='pesonal_email',
        ),
    ]
